In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA
from yellowbrick.cluster import KElbowVisualizer

import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("Transformed_files/clustred.csv")

In [4]:
df.head()

,Income,Kidhome,Teenhome,Recency,NumWebVisitsMonth,Complain,Age,Years_Customer,Days_Customer,TotalMntSpent,TotalNumPurchases,Total_Acc_Cmp,Year_Joined,Month_Joined,Day_Joined,Age_Group,Children,Partner,Education_Level,Cluster
0,58138.0,0,0,58,7,0,57,1,663,1617.0,25.0,1.0,2013,September,Tuesday,Middel Aged,0.0,No,Graduate,1
1,46344.0,1,1,38,5,0,60,1,113,27.0,6.0,0.0,2013,March,Saturday,Middel Aged,2.0,No,Graduate,1
2,71613.0,0,0,26,4,0,49,1,312,776.0,21.0,0.0,2013,August,Wednesday,Middel Aged,0.0,Yes,Graduate,3
3,26646.0,1,0,26,6,0,30,1,139,53.0,8.0,0.0,2013,February,Monday,Adult,1.0,Yes,Graduate,0
4,58293.0,1,0,94,5,0,33,1,161,422.0,19.0,0.0,2013,January,Sunday,Adult,1.0,Yes,Postgraduate,3

In [5]:
dataC = df.copy()
scaler = StandardScaler()
dataC = scaler.fit_transform(dataC)
scaled_data = pd.DataFrame(dataC, columns= data.columns)

ValueError: could not convert string to float: 'September'